services:
  backend:
    image: backend
    container_name: backend
    build: ./backend
    attach: false
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app
    environment:
      - FLASK_APP=/app
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run --reload

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    attach: false
    restart: always
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev